In [ ]:
def add(x) :
  return x + 5

print(add(10))

15

In [ ]:
add = lambda x: x+5
print(add(10))

15

In [ ]:
import pandas as pd
ages = pd.Series([20, 25, 30, 35])
ages.apply(lambda x: x+5)

0    25
1    30
2    35
3    40
dtype: int64

In [ ]:
import pandas as pd
df = pd.read_csv('/content/sample_data/california_housing_train.csv')
country_group = df.groupby('housing_median_age')
country_python = country_group['median_income'].apply(lambda x: x.mean())
country_python

housing_median_age
1.0     4.756800
2.0     5.074237
3.0     5.572013
4.0     5.196055
5.0     4.732460
6.0     4.463901
7.0     4.368441
8.0     4.412988
9.0     4.357513
10.0    4.126004
11.0    4.029663
12.0    4.003208
13.0    4.145092
14.0    4.148454
15.0    4.003953
16.0    4.288458
17.0    3.929201
18.0    3.954591
19.0    3.833244
20.0    3.749984
21.0    3.870417
22.0    3.941335
23.0    3.963371
24.0    3.921026
25.0    4.135890
26.0    4.071895
27.0    3.859375
28.0    3.813176
29.0    3.633556
30.0    3.580732
31.0    3.619995
32.0    3.800399
33.0    3.862161
34.0    3.959488
35.0    3.909391
36.0    3.973530
37.0    3.684131
38.0    3.463225
39.0    3.395865
40.0    3.432734
41.0    3.149125
42.0    3.447088
43.0    3.238897
44.0    3.507043
45.0    3.739467
46.0    3.357832
47.0    3.278638
48.0    3.526261
49.0    3.547657
50.0    3.472372
51.0    3.670503
52.0    3.943037
Name: median_income, dtype: float64

In [ ]:

country_total = country_group.size().rename('total_count')
country_python_sorted = country_python.sort_values(ascending=False)
python_df = pd.concat([country_python, country_total], axis='columns')
python_df

                    median_income  total_count
housing_median_age
1.0                      4.756800            2
2.0                      5.074237           49
3.0                      5.572013           46
4.0                      5.196055          161
5.0                      4.732460          199
6.0                      4.463901          129
7.0                      4.368441          151
8.0                      4.412988          178
9.0                      4.357513          172
10.0                     4.126004          226
11.0                     4.029663          208
12.0                     4.003208          192
13.0                     4.145092          249
14.0                     4.148454          347
15.0                     4.003953          416
16.0                     4.288458          635
17.0                     3.929201          576
18.0                     3.954591          478
19.0                     3.833244          412
20.0                     3.749984          383
21.0                     3.870417          373
22.0                     3.941335          323
23.0                     3.963371          382
24.0                     3.921026          389
25.0                     4.135890          461
26.0                     4.071895          503
27.0                     3.859375          397
28.0                     3.813176          400
29.0                     3.633556          374
30.0                     3.580732          384
31.0                     3.619995          384
32.0                     3.800399          458
33.0                     3.862161          513
34.0                     3.959488          567
35.0                     3.909391          692
36.0                     3.973530          715
37.0                     3.684131          437
38.0                     3.463225          318
39.0                     3.395865          302
40.0                     3.432734          249
41.0                     3.149125          232
42.0                     3.447088          308
43.0                     3.238897          286
44.0                     3.507043          296
45.0                     3.739467          235
46.0                     3.357832          196
47.0                     3.278638          175
48.0                     3.526261          135
49.0                     3.547657          111
50.0                     3.472372          112
51.0                     3.670503           32
52.0                     3.943037         1052

In [ ]:
python_df.rename(columns={'count':Total})

In [ ]:

python_df['Percent_MedianIncome_Per_TotalCount'] = (python_df['median_income'] / python_df['total_count']) * 100
python_df

,median_income,total_count,Percent_MedianIncome_Per_TotalCount
housing_median_age,,,
1.0,4.756800,2,237.840000
2.0,5.074237,49,10.355585
3.0,5.572013,46,12.113072
4.0,5.196055,161,3.227364
5.0,4.732460,199,2.378121
6.0,4.463901,129,3.460388
7.0,4.368441,151,2.893007
8.0,4.412988,178,2.479207
9.0,4.357513,172,2.533438
10.0,4.126004,226,1.825666
11.0,4.029663,208,1.937338
12.0,4.003208,192,2.085004
13.0,4.145092,249,1.664696
14.0,4.148454,347,1.195520
15.0,4.003953,416,0.962489
16.0,4.288458,635,0.675348
17.0,3.929201,576,0.682153
18.0,3.954591,478,0.827320
19.0,3.833244,412,0.930399
20.0,3.749984,383,0.979108
21.0,3.870417,373,1.037645
22.0,3.941335,323,1.220227
23.0,3.963371,382,1.037532
24.0,3.921026,389,1.007976
25.0,4.135890,461,0.897156
26.0,4.071895,503,0.809522
27.0,3.859375,397,0.972135
28.0,3.813176,400,0.953294
29.0,3.633556,374,0.971539
30.0,3.580732,384,0.932482
31.0,3.619995,384,0.942707
32.0,3.800399,458,0.829781
33.0,3.862161,513,0.752858
34.0,3.959488,567,0.698322
35.0,3.909391,692,0.564941
36.0,3.973530,715,0.555738
37.0,3.684131,437,0.843051
38.0,3.463225,318,1.089065
39.0,3.395865,302,1.124459
40.0,3.432734,249,1.378608
41.0,3.149125,232,1.357381
42.0,3.447088,308,1.119185
43.0,3.238897,286,1.132481
44.0,3.507043,296,1.184812
45.0,3.739467,235,1.591263
46.0,3.357832,196,1.713180
47.0,3.278638,175,1.873508
48.0,3.526261,135,2.612045
49.0,3.547657,111,3.196087
50.0,3.472372,112,3.100332
51.0,3.670503,32,11.470322
52.0,3.943037,1052,0.374813